export const TRANSLATIONS = {
    en_US: {
      Username: 'Username',
      Password: 'Password',
      Forgot_password: 'Forgot password?',
      Sign_in: 'Sign in',
      Dashboard: 'Dashboard',
      RegistNumber: 'RegistNumber',
      Add_RegistNumber: 'Add Registnumber',
      Save: 'Save',
      Number: 'Number',
      Studentnumber: 'StudentNumber',
      ParticipantNumber: 'ParticipantNumber',
      CommitmentNumber: 'CommitmentNumber',
      Previous:'Previous',
      Next:'Next',
      Show_entries:'Show entries',
      Show:'Show',
      Entries:'entries',
      Show_page:'Showing page',
      User: 'User',
      Add_User: 'Add User',
      UserName: 'UserName',
      Email: 'Email',
      Active: 'Active',
      Action: 'Action',
      New_user: 'New User',
      ConfirmPassword: 'ConfirmPassword',
      Role: 'Role',
      PhoneNumber: 'PhoneNumber',
      Edit_user: 'Edit User',
      View_user: 'View User',
      The_user_has_been_deleted: 'The user has been deleted!',
      Log: 'Log',
      TypeChange: 'TypeChange',
      PKRecord: 'PKRecord',
      ReasonChange: 'ReasonChange',
      DateChange: 'DateChange',
      Id: 'Id',
      Entity: 'Entity',
      NewValue: 'NewValue',
      OldValue: 'OldValue',
      FieldName: 'FieldName',
      ModifiedOn: 'ModifiedOn'
    },


    nl_BE: {
      Username: 'Gebruikersnaam',
      Password: 'Wachtwoord',
      Forgot_password: 'Wachtwoord vergeten?',
      Sign_in: 'Aanmelden',
      Dashboard: 'Dashboard',
      RegistNumber: 'Verbintenisnummer',
      Add_RegistNumber: 'Toevoegen Verbintenisnummer',
      Save: 'Opslaan',
      Number: 'Nummer',
      Studentnumber: 'Deelnemernummer',
      ParticipantNumber: 'Deelnemernummer',
      CommitmentNumber: 'Verbintenisnummer',
      Previous:'Vorige',
      Next:'Volgende',
      Show_entries:'Toon records',
      Show:'Tonen',
      Entries:'records',
      Show_page:'Pagina weergegeven',
      User: 'Gebruiker',
      Add_User: 'Toevoegen Gebruiker',
      UserName: 'GebruikerNaam',
      Email: 'Email',
      Active: 'Actief',
      Action: 'Actie',
      New_user: 'Nieuwe Gebruiker',
      ConfirmPassword: 'Bevestigen Wachtwoord',
      Role: 'Rol',
      PhoneNumber: 'TelefoonAantal',
      Edit_user: 'Bewerk Gebruiker',
      View_user: 'Uitzicht Gebruiker',
      The_user_has_been_deleted: 'De gebruiker is verwijderd!',
      Log: 'Log',
      TypeChange: 'TypeWijziging',
      PKRecord: 'PKRecord',
      ReasonChange: 'ReasonChange',
      DateChange: 'DatumWijziging',
      Id: 'Id',
      Entity: 'Entiteit',
      NewValue: 'NieuweWaarde',
      OldValue: 'OudeWaarde',
      FieldName: 'VeldNaam',
      ModifiedOn: 'GewijzigdOp'
    }
  };